Feature/views
Maks-well-88/TestGuru pull request #7
Opened 2021-09-14 22:10 UTC by Maks-well-88

2021-09-15 07:04 UTC, BubuntuClu requested changes

2021-09-15 07:04 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id])
дублирование кода. просто в колбэк экшен добавь

2021-09-15 07:04 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +  def question_header(question)
только этот метод относится к вопросу. два остальных общие методы, они не должны находиться в `QuestionsHelper`

2021-09-15 07:04 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +<h1><%= question_header(@question) %></h1>
выглядит так, как будто можно поместить эту строку внутрь `form`

2021-09-15 07:06 UTC, BubuntuClu requested changes

2021-09-15 07:06 UTC, BubuntuClu commented on app/views/tests/_test.html.erb
> +</tr>
нужно добавить ссылки на просмотра/удаления/редактирования теста

2021-09-15 07:06 UTC, BubuntuClu requested changes

2021-09-15 07:06 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
>    def index
этот метод не нужен.
>Список вопросов теста должен выводиться на той же странице, что и сам тест

он переезжает в tests#show

2021-09-16 07:18 UTC, BubuntuClu requested changes

2021-09-16 07:18 UTC, BubuntuClu commented on app/views/tests/_form.html.erb
> +  <p><%= f.label :title %></p>
отделить бы параметры друг от друга пустой строкой. сейчас стена текста все сливается

```
  <p><%= f.label :level %></p>
  <p><%= f.number_field  :level %></p>

  <p><%= f.label :category_id %></p>
  <p><%= f.collection_select :category_id, Category.order(:title), :id, :title %></p>
```
о таком разделении речь

2021-09-16 07:18 UTC, BubuntuClu commented on app/views/tests/show.html.erb
> +<h2>Тест: "<%= @test.title %>"</h2>
ты выводишь только заголовок теста, а должен быть еще список вопросов этого теста

2021-09-16 07:18 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test = Test.create(test_params)
`Test.new`
если ты делаешь `create` и потом `save`, то это лишний запрос в БД порождает

2021-09-16 13:07 UTC, Maks-well-88 commented on app/views/tests/show.html.erb
> +<h2>Тест: "<%= @test.title %>"</h2>
Странно. У меня все в порядке, все вопросы теста выводятся.
Я это сделал так: в методе show тест-контроллера я просто сделал редирект на test_questions_path(@test) на view index.html.erb для questions. Поэтому там и был def index; end. Но и без него все работает.

2021-09-16 17:09 UTC, BubuntuClu commented on app/views/tests/show.html.erb
> +<h2>Тест: "<%= @test.title %>"</h2>
>Я это сделал так: в методе show тест-контроллера я просто сделал редирект на test_questions_path(@test) на view index.html.erb для questions.

это очень плохой способ. ты заходишь на одну страницу, а там идет редирект на другую. вот сейчас норм сделано

2021-09-16 17:09 UTC, BubuntuClu commented on app/views/tests/_form.html.erb
> +
между каждым не надо. по парам. у тебя label и форма ввода для занчения. вот по парам отделять стоит, чтобы логически делилось

2021-09-16 17:51 UTC, merged